added support for info_overlay and infodecal
REDxEYE/SourceIO pull request #83
Opened 2021-03-06 17:50 UTC by half5life

2021-03-06 18:06 UTC, REDxEYE requested changes
Please fix all mentioned issues and I happily merge your PR

2021-03-06 18:06 UTC, REDxEYE commented on source1/bsp/entities/base_entity_handler.py
> +            ]
Please, use snake_case variable names

2021-03-06 18:06 UTC, REDxEYE commented on source1/bsp/import_bsp.py
> +                    vert[2] = temp
Can be replaced with a bit more readable 
`vert[1], vert[2] = vert[2], vert[1]`

2021-03-06 18:06 UTC, REDxEYE commented on source1/bsp/import_bsp.py
> +                bpy.ops.object.mode_set()
mesh_data.flip_normals()

2021-03-06 18:06 UTC, REDxEYE commented on source1/bsp/import_bsp.py
> +    def rotate_infodecals(self):
add an underscore to utility function name

2021-03-06 18:06 UTC, REDxEYE commented on source1/bsp/import_bsp.py
> +                rayF = func.ray_cast(obj.location, (dirF[0], dirF[1], dirF[2]))
snake_case variable names

2021-03-06 18:06 UTC, REDxEYE commented on source1/bsp/import_bsp.py
> +                if (rayF[0]):
redundant parentheses

2021-03-06 18:06 UTC, REDxEYE commented on source1/bsp/lumps/overlay_lump.py
> +        return self
Add new line here

2021-03-06 18:06 UTC, REDxEYE commented on source1_operators.py
> +        bsp_map.rotate_infodecals()
Move this function call into load_overlays method

2021-03-06 18:34 UTC, ShadelessFox commented
Consider checking for the existence of requested material:

```
[INFO    ]-[decal.bsp] Loading map "C:\Users\ShadelessFox\Desktop\decal.bsp"
[DEBUG   ]-[decal.bsp] Adding map pack file to content manager
[INFO    ]-[content_manager] Requesting materials\dev\dev_measurecrate01.vmt file
Python: Traceback (most recent call last):
  File "E:\SteamLibrary\steamapps\common\Blender\2.92\scripts\addons\SourceIO\source1_operators.py", line 96, in execute
    bsp_map.load_entities()
  File "E:\SteamLibrary\steamapps\common\Blender\2.92\scripts\addons\SourceIO\source1\bsp\import_bsp.py", line 92, in load_entities
    self.entity_handler.load_entities()
  File "E:\SteamLibrary\steamapps\common\Blender\2.92\scripts\addons\SourceIO\source1\bsp\entities\base_entity_handler.py", line 298, in load_entities
    if not self.handle_entity(entity_data):
  File "E:\SteamLibrary\steamapps\common\Blender\2.92\scripts\addons\SourceIO\source1\bsp\entities\base_entity_handler.py", line 312, in handle_entity
    handler_function(entity_object, entity_data)
  File "E:\SteamLibrary\steamapps\common\Blender\2.92\scripts\addons\SourceIO\source1\bsp\entities\base_entity_handler.py", line 674, in handle_infodecal
    tex_name = bpy.data.materials[material_name].node_tree.nodes["$basetexture"].image.name
KeyError: 'bpy_prop_collection[key]: key "dev_measurecrate01" not found'
```

2021-03-06 18:39 UTC, ShadelessFox commented
```
OrderedDict([('origin', '-384 128 273'),
             ('angles', '0 0 0'),
             ('classname', 'info_player_start'),
             ('hammerid', 156)])
GLump "sprp" offset: 36 size: 12
GLump "dprp" offset: 48 size: 12
Python: Traceback (most recent call last):
  File "E:\SteamLibrary\steamapps\common\Blender\2.92\scripts\addons\SourceIO\source1_operators.py", line 99, in execute
    bsp_map.rotate_infodecals()
  File "E:\SteamLibrary\steamapps\common\Blender\2.92\scripts\addons\SourceIO\source1\bsp\import_bsp.py", line 359, in rotate_infodecals
    for func in bpy.data.collections['func_brush'].all_objects:
KeyError: 'bpy_prop_collection[key]: key "func_brush" not found'
```

The game used for testing is Half-Life 2: [decal.zip](https://github.com/REDxEYE/SourceIO/files/6095882/decal.zip)

2021-03-07 10:10 UTC, REDxEYE approved these changes
Much better now. Let's do some testing and if everything will be stable, I'll merge it into master.
For now, I create an experimental release with this feature

2021-03-15 11:18 UTC, merged